name: 'Environment Inspector'
description: 'Displays comprehensive environment variables and system information for GitHub Actions debugging'

author: 'LTomer'

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'