name: 'Environment Variables'
description: 'Shows all environment variables grouped by prefix'
author: 'LTomer'

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'