name: 'My Custom Action'
description: 'Say Hello'
author: 'LTomer'

inputs:
  name:
    description: 'The name of the person to greet'
    required: true
    default: 'World'
    
runs:
  using: 'node24'
  main: 'dist/index.js'