name: Check Environment Variables Custom Action

on:
  workflow_dispatch:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Environment Variables'
        uses: ./
